### ISSUE TITLE
Library not compiling

### ISSUE THREAD

**Issue by SlamaFR** [jwpeterson/mp-quadrature#1] opened 2020-10-07 11:54 UTC
Hi!

So basically, I was trying to install your library but "make" threw several errors whilst compiling sources:
```
Compiling drivers/dubiner_verify_double.C...
In file included from drivers/dubiner_verify_double.C:2:
In file included from ./include/dubiner.h:7:
./include/matrix.h:212:15: error: call to 'abs' is ambiguous
          if (abs(val) < 1.e-30)
              ^~~
drivers/dubiner_verify_double.C:146:17: note: in instantiation of member function 'Matrix<double>::print' requested here
      mass_sums.print();
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:110:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:112:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
1 error generated.
make[1]: *** [drivers/dubiner_verify_double.lo] Error 1
make: *** [all] Error 2
```

I hope you can fix this!

Regards, Slama.

**Comment by jwpeterson** [comment] 2020-10-07 13:51
Thanks for your bug report. I pushed a commit which attempts to fix the line you mentioned, but scanning through the header I think there will be other lines that trigger the same error. So I will have to come up with a more complete fix at some point.

**Comment by jwpeterson** [comment] 2020-10-07 15:40
I merged a more complete fix in d448684, so hopefully that works for you as well.

**Comment by SlamaFR** [comment] 2020-10-08 13:49
Your fix actually fixed things up. Now when compiling, I got some weak warnings BUT, I got this error :
```
Compiling drivers/nlopt_test.C...
drivers/nlopt_test.C:7:3: error: use of undeclared identifier 'std'
  std::cout << "This driver requires nlopt. Install nlopt and then rerun configure, "
  ^
drivers/nlopt_test.C:9:35: error: use of undeclared identifier 'std'
            << "its location." << std::endl;
                                  ^
2 errors generated.
make[1]: *** [drivers/nlopt_test.lo] Error 1
rm drivers/compute_residuals_1D.lo drivers/dubiner_verify_jacobi.lo drivers/gm_rule.lo drivers/lu.lo drivers/gatermann_search.lo drivers/conical_product_2D.lo drivers/dubiner_verify_double.lo drivers/jacobi_rule.lo drivers/dubiner_verify.lo drivers/conical_product_3D.lo drivers/gatermann.lo
make: *** [all] Error 2
```

Thank you for being such active on your repo, and hope you can fix this as well.

**Comment by SlamaFR** [comment] 2020-10-08 13:50
Nevermind, I need to install someting, just ignore my last call

**Comment by SlamaFR** [comment] 2020-10-08 13:58
Well, supposing by "nlopt" you mean this library https://github.com/stevengj/nlopt, I did installed it ant re-ran ./configure, but I got the same error.. This is pretty frustrating, if you know what is going on, I would like you to explain :)

**Comment by jwpeterson** [comment] 2020-10-08 14:06
This was a real issue which I never observed because I always built with nlopt enabled. It should be fixed in 14e01d3. 

Note that if you installed nlopt after you ran configure, you will have to go back and re-run configure again, passing `--with-nlopt-include` and `--with-nlopt-lib` for it to be picked up by the build system.

**Comment by SlamaFR** [comment] 2020-10-08 14:55
I am really sorry to insist but whenever you fix something, it fails a little bit further
```
drivers/nlopt_test.C:45:13: error: functions that differ only in their return type cannot be overloaded
std::string nlopt_result_to_string(nlopt_result res);
~~~~~~~~~~~ ^
/usr/local/include/nlopt.h:178:28: note: previous declaration is here
NLOPT_EXTERN(const char *) nlopt_result_to_string(nlopt_result algorithm);
                   ~~~~~~  ^
drivers/nlopt_test.C:1542:59: error: call to 'nlopt_result_to_string' is ambiguous
          std::cout << "nlopt converged with reason: " << nlopt_result_to_string(res) << std::endl;
                                                          ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/nlopt.h:178:28: note: candidate function
NLOPT_EXTERN(const char *) nlopt_result_to_string(nlopt_result algorithm);
                           ^
drivers/nlopt_test.C:45:13: note: candidate function
std::string nlopt_result_to_string(nlopt_result res);
            ^
drivers/nlopt_test.C:1637:13: error: functions that differ only in their return type cannot be overloaded
std::string nlopt_result_to_string(nlopt_result res)
~~~~~~~~~~~ ^
/usr/local/include/nlopt.h:178:28: note: previous declaration is here
NLOPT_EXTERN(const char *) nlopt_result_to_string(nlopt_result algorithm);
                   ~~~~~~  ^
3 warnings and 3 errors generated.
make[1]: *** [drivers/nlopt_test.lo] Error 1
make: *** [all] Error 2
```

**Comment by jwpeterson** [comment] 2020-10-08 15:14
Hmm... I'm afraid this time the problem is in the nlopt library, so you may want to submit a bug report to them regarding it. The last version of nlopt that I tried, 2.4.2, did not seem to have this problem, so possibly you could try that version. Anyway, nlopt is optional so you could also just configure with it disabled and you shouldn't see this error any longer.

Thanks, I appreciate your feedback on the issues you are finding.

**Comment by jwpeterson** [comment] 2020-10-08 15:33
Actually, I misspoke. It looks like I wrote a function `nlopt_result_to_string` and it conflicts with a function of the same name defined in newer versions of nlopt.h. I should be able to fix this...

**Comment by jwpeterson** [comment] 2020-10-08 15:39
OK, this issue should now be fixed in 2acbd76.

**Comment by SlamaFR** [comment] 2020-10-08 16:03
Ok, your fix did fixed it. Now all your code compiles, congratulations!

With that said, I need to ask you, how to finish the installation and how to use your library?

**Comment by jwpeterson** [comment] 2020-10-08 16:17
> how to finish the installation and how to use your library?

There's no make install currently. The idea is to start with one of the programs in the "drivers" directory, and modify it or create a new driver to solve the particular problem you are interested in. If you add a new file foo.C in the drivers directory, you should be able to compile it automatically just by typing "make", no build system modifications should be required.

**Comment by jwpeterson** [comment] 2020-10-08 16:21
BTW now that everything compiled, you may want to run "./run_tests.sh" from the top-level directory. This will actually run several of the driver executables so it's a good way to check that the build is correct.

**Comment by SlamaFR** [comment] 2020-10-08 16:58
> you may want to run "./run_tests.sh"
Ok tests ran nicely, everything is working

I will try playing with your drivers to understand how it works. I'm so grateful, you just saved my semester ;)
Thank you so much!

**Closed as completed** 2020-10-08 17:20 UTC
